[project]
name = "image-generator-of-874wokiite"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.37.20",
    "openai>=1.68.2",
    "requests>=2.32.3",
]

[tool.taskipy.tasks]
build = "bash scripts/build.sh"
